cd /t3home/fglessge/CMSSW_10_1_0/src/Xbb/python/
Task: run
Pwd: /t3home/fglessge/CMSSW_10_1_0/src/Xbb/python
Host: t3wn51
User: fglessge
StartTime: 2022-02-15 17:27:12

Parsing files in Zll2017config...

python ./sys_new.py --addCollections KinematicFit.fitter --fileList base64:eNolx7EKgzAUQNEvsu9FTdS5HaRocRChU4jJ0witCUkc/PuCvcvhQkwuEKzBHR68PaO027pGsPMMezr8hyJM7TwPLqaX2h3kyCqYGIPH+0kpjq7rZJ9xlO2YCcTkakQ5HjvdBy5ZMdKUfZVZg/K27/rMn8luqgZeCqapysnosl6MLnlTmEpzQVhwIRRpqpTCpS6WnNA0JROGcOGAV/LPdZACkeS34Fz6AdarQKg= --sampleIdentifier DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8 --config /t3home/fglessge/CMSSW_10_1_0/src//Xbb/python/logs_Zll2017//kinfit/config//submission_20220215_172539.ini --inputDir KINFITin --outputDir KINFITout
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] No such file

len(filelist) 1 filelist[0]: /store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root
INput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys/
OUTput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out
collections to add: ['KinematicFit.fitter']
after parsing: ['KinematicFit.fitter']
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys//DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/tree_5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5_000000_000000_0000_5_e8d654251111833c3004d29dc364255354607795b3e8125b6240ac91.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys//DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/tree_5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5_000000_000000_0000_5_e8d654251111833c3004d29dc364255354607795b3e8125b6240ac91.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys//DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/tree_5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5_000000_000000_0000_5_e8d654251111833c3004d29dc364255354607795b3e8125b6240ac91.root[0m
INFO: # files chained: 0
trying fallback... 1
FO: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root[0m
INFO: # files chained: 0
[31mERROR: file does not exist or is broken, will be SKIPPED![0m
Traceback (most recent call last):
  File "./sys_new.py", line 301, in <module>
    xr.run()
  File "./sys_new.py", line 281, in run
    raise Exception("ProcessingIncomplete")
Exception: ProcessingIncomplete
--------------------------------------------------------------------------------
exit code: 1
EndTime: 2022-02-15 17:27:22
duration (real time): 0 minutes
--- RETRY ---
python ./sys_new.py --addCollections KinematicFit.fitter --fileList base64:eNolx7EKgzAUQNEvsu9FTdS5HaRocRChU4jJ0witCUkc/PuCvcvhQkwuEKzBHR68PaO027pGsPMMezr8hyJM7TwPLqaX2h3kyCqYGIPH+0kpjq7rZJ9xlO2YCcTkakQ5HjvdBy5ZMdKUfZVZg/K27/rMn8luqgZeCqapysnosl6MLnlTmEpzQVhwIRRpqpTCpS6WnNA0JROGcOGAV/LPdZACkeS34Fz6AdarQKg= --sampleIdentifier DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8 --config /t3home/fglessge/CMSSW_10_1_0/src//Xbb/python/logs_Zll2017//kinfit/config//submission_20220215_172539.ini --inputDir KINFITin --outputDir KINFITout
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] No such file

len(filelist) 1 filelist[0]: /store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root
INput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys/
OUTput samples:	root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/kinfit_out
collections to add: ['KinematicFit.fitter']
after parsing: ['KinematicFit.fitter']
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys//DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/tree_5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5_000000_000000_0000_5_e8d654251111833c3004d29dc364255354607795b3e8125b6240ac91.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys//DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/tree_5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5_000000_000000_0000_5_e8d654251111833c3004d29dc364255354607795b3e8125b6240ac91.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys//DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/tree_5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5_000000_000000_0000_5_e8d654251111833c3004d29dc364255354607795b3e8125b6240ac91.root[0m
INFO: # files chained: 0
trying fallback... 1
FO: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root
INFO: reading part  1  of  1
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root, trying 2 more times...
INFO: wait 1 seconds before trying again
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_VOMS_DIR = /etc/grid-security/vomsdir
DEBUG: X509_USER_PROXY = /t3home/fglessge/.x509up_u742
INFO: file was not found:root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root, trying 1 more times...
INFO: wait 2 seconds before trying again
[31mERROR: file is missing: root://t3dcachedb03.psi.ch:1094//pnfs/psi.ch/cms/trivcat/store/user/fglessge/VHbb/Zll/VHbbPostNano2017_V11/2020_06_08/sys///store/group/phys_higgs/hbb/ntuples/VHbbPostNano/2017/V11/DYJetsToLL_M-50_HT-600to800_TuneCP5_13TeV-madgraphMLM-pythia8/5461ce72edc48fdc4593d7c56e03566aece7aa0f83f2e0d9416de0f5/000000_000000/0000/tree_5.root[0m
INFO: # files chained: 0
[31mERROR: file does not exist or is broken, will be SKIPPED![0m
Traceback (most recent call last):
  File "./sys_new.py", line 301, in <module>
    xr.run()
  File "./sys_new.py", line 281, in run
    raise Exception("ProcessingIncomplete")
Exception: ProcessingIncomplete
exit code: 1
duration (real time): 0 minutes, including retry

Exiting runAll.sh

